apiVersion: apps/v1
kind: Deployment
metadata:
  name: acheeve-deployment
  labels:
    app: acheeve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acheeve
  template:
    metadata:
      labels:
        app: acheeve
    spec:
      containers:
        - name: acheeve
          image: acheeve/acheeve.app:latest
          ports:
            - containerPort: 3000
        env:
        - name: NITRO_PORT
          value: 3000
        - name: NITRO_HOST
          value: 0.0.0.0
        - name: NITRO_PRESET
          value: node_cluster
          