stages:
  - deploy

prod-deploy:
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  stage: deploy
  script:
    - kubectl --kubeconfig=k8s/kub-config.yaml get pods
    - kubectl cluster-info
    - kubectl create secret docker-registry regcred --docker-server="$CI_REGISTRY" --docker-username="$CI_REGISTRY_USER" --docker-password="$CI_REGISTRY_PASSWORD"
    - kubectl delete deployment acheeve-deployment
    - kubectl apply -f k8s/acheeve.yaml
