apiVersion: apps/v1
kind: Deployment
metadata:
  name: acheeve-deployment
  labels:
    app: acheeve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acheeve
  template:
    metadata:
      labels:
        app: acheeve
    spec:
      containers:
        - name: acheeve
          image: registry.gitlab.com/acheeve.app/acheeve
          ports:
            - containerPort: 3000
          env:
            - name: NITRO_PORT
              value: '3000'
            - name: NITRO_HOST
              value: 0.0.0.0
            - name: NITRO_PRESET
              value: node_cluster
            - name: SUPABASE_URL
              value: https://rpoeffpbbnljlyhptgks.supabase.co
            - name: SUPABASE_KEY
              value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwb2VmZnBiYm5samx5aHB0Z2tzIiwicm9sZSI6ImFub24iLCJpYXQiOjE2Nzc5NTkyMjQsImV4cCI6MTk5MzUzNTIyNH0.62rHuLB3ePaIz4Rg9zIB-HnHueUUH8yXUqzk8HjhAN8
            - name: DATABASE_URL
              value: postgres://postgres:DhTtj8QYp1xUiA9W@db.rpoeffpbbnljlyhptgks.supabase.co:6543/postgres
            - name: SUPABASE_SERVICE_KEY
              value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwb2VmZnBiYm5samx5aHB0Z2tzIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY3Nzk1OTIyNCwiZXhwIjoxOTkzNTM1MjI0fQ.M8VzpS9vTFg_PbskBZpiVf_xxvWhRNGkjNQrq88Lsjk
      imagePullSecrets:
        - name: regcred
